### PR TITLE
Remove scrutinizer config

### PR DESCRIPTION
**Pull request by ciaranmcnulty**
It's rarely looked at and we can use Actions for tools instead (#1318)

### CODE REVIEW

**Comment by drupol** [comment]
I don't think Github actions can do what Scrutinizer do.

I like Scrutinizer to tell me the percentage of code coverage and the code quality. AFAIK, Github Actions doesn't do that.

**Comment by ciaranmcnulty** [comment]
I mean using open-source tools inside actions

**Comment by jakzal** [comment]
@ciaranmcnulty what about the badge in README?

**Comment by stof** [comment]
@drupol Scrutinizer was not setup for code coverage anyway, only for static analysis

**Pull request merged**
