### PR TITLE
ci: Enable builds on MacOS and Windows.

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- [x] Enable builds on MacOS and Windows
- [x] Originates from #1380 (and a chat on Slack)

### CODE REVIEW

**Review by jakzal — APPROVED** [review]

**Comment by ciaranmcnulty** [comment]
Do you want to remove the not-failing test?

**Comment by drupol** [comment]
Give me a bit of time, I'll continue after my work day.

I would like to find a failing test.

**Comment by arnaspet** [comment]
This one actually fails for me locally.
```bash
➜ bin/phpspec run spec/PhpSpec/CodeAnalysis/TokenizedNamespaceResolverSpec.php --no-ansi
PhpSpec/CodeAnalysis/TokenizedNamespaceResolver                                              
 129  - it resolves types and highlight issue 1380
      expected "App\Factories\RabbitMQFac...", but got "Baz\RabbitMQFactory".

/  skipped: 0%  /  pending: 0%  /  passed: 87%  /  failed: 12%  /  broken: 0%   /  8 examples
1 specs
8 examples (7 passed, 1 failed)
30ms

```

**Comment by drupol** [comment]
Thanks @arnaspet it helps a lot!

Extremely curious that it's not detected by CI.

@ciaranmcnulty Any clue on this?

**Comment by ciaranmcnulty** [comment]
Nope, no idea

**Comment by arnaspet** [comment]
I actually have a working regexp written, but I don't know how to justify this change without a failing CI.

**Comment by ciaranmcnulty** [comment]
I'd really like to know what the difference in environments is!

**Comment by drupol** [comment]
I removed the commits related to the new tests that I was trying to introduce now that it has been fixed upstream (see #1380).

**Comment by drupol** [comment]
Thanks!

**Pull request merged**
