### PR TITLE
Updating PHPUnit version

### PR DESCRIPTION
**Pull request by Sam-Burns**
Updates PHPUnit to `5.x` if possible, which will be installed if using PHP 7.

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
I'm not sure there's a good reason to disallow 5.0-5.2?

**Comment by Sam-Burns** [comment]
Could change it to `~4.4|~5.0` if you prefer, but it's going to install `5.3` in PHP 7 or `4.8` in PHP 5 anyway, isn't it?

**Comment by ciaranmcnulty** [comment]
I'd prefer that - if someone's tagged phpunit `5.0.4` or something in their composer config they wouldn't be able to install

**Comment by ciaranmcnulty** [comment]
Thanks for stopping this!

**Pull request merged**
