### PR TITLE
Don't cache vendor folder

### PR DESCRIPTION
**Pull request by ciaranmcnulty**
Seeing if this fixes the appveyor build...

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Well this fixes things, a more nuanced fix can come later.

**Comment by stof** [comment]
Caching the composer cache is better than caching the vendor folder: an existing vendor folder impacts the dependency resolution, which can result into issues if it is corrupted.

**Comment by ciaranmcnulty** [comment]
I'm not sure what was breaking, I suspect the `.git` files were not being included in the cache

**Comment by ciaranmcnulty** [comment]
@sroze has pointed out https://github.com/symfony/symfony/pull/17171/files which might be a good option for future

**Pull request merged**
