### PR TITLE
Add string contain matcher

### PR DESCRIPTION
**Pull request by mheki**
This PR adds matcher which helps to check if the string contains given substring.
It allows to write: `$this->getSlug()->shouldContain('foo');` and can help to write more readable and simpler examples.

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Can you please add a feature to the behat coverage as well?

**Comment by ciaranmcnulty** [comment]
And come to think of it, the docs could be updated as part of this same PR

**Comment by mheki** [comment]
Sure @ciaranmcnulty

**Comment by mheki** [comment]
Both added

**Comment by ciaranmcnulty** [comment]
Looks good, thanks!

**Pull request merged**
