### PR TITLE
Convert docs to Hugo

### PR DESCRIPTION
**Pull request by jaylinski**

### CODE REVIEW

**Comment by drupol** [comment]
Good idea :)

**Comment by jaylinski** [comment]
@drupol We'll see :sweat_smile:  (it isn't quite ready yet)

**Comment by ciaranmcnulty** [comment]
We currently host with readthedocs.io, does that support Hugo?

**Comment by GrahamCampbell** [comment]
No. Hugo is a static site builder? It would be to replace readthedocs.io as the "thing that renders the pages" I think.

**Comment by jaylinski** [comment]
I'm using GitHub actions to automatically build the docs with Hugo and push them to the `gh-pages` branch.

WIP: https://jaylinski.github.io/phpspec/

Hugo is not specifically made for docs, so it lacks some features. I'll explain it in a new PR so you can decide if you want to migrate to Hugo or stick with readthedocs (which seems broken).

**Comment by drupol** [comment]
There's this very new theme that could fit for documentation: https://themes.gohugo.io/compose/

**Comment by drupol** [comment]
> WIP: https://jaylinski.github.io/phpspec/

Amazing wip, nice work !

I definitely vote for Hugo :-)
That said, it would be nice to know why readthedocs is broken, I never had any issue with ReadTheDocs and it's working well for my own projects.

**Pull request closed without merging**
