### PR TITLE
5.0 add more typehints

### PR DESCRIPTION
**Pull request by kix**
While working on #1206, I've also found several methods that could have return type hints. Also, CS fixed so that return typehints all have no space before colons.

`ConsoleIO` had a merge conflict in it; resolved to `@return ?string` instead of `@return string|null`

### CODE REVIEW

**Comment by jakzal** [comment]
Seems you created your branch off the old master.

**Comment by jakzal** [comment]
@kix ah, i guess 5.0 needs to have recent fixes merged in, @ciaranmcnulty ?

**Comment by ciaranmcnulty** [comment]
Yep just need to resolve a conflict in appveyor when I’m back on WiFi

**Comment by ciaranmcnulty** [comment]
Can you rebase against 5.0 please?

**Pull request merged**
