### PR TITLE
Add support for symfony 5 #SymfonyHackday

### PR DESCRIPTION
**Pull request by alexander-schranz**
#SymfonyHackday 

**TODO**

 - [ ] Needs behat/behat update Behat/Behat#1247 or Behat/Behat#1256
 - [x] Update Event Dispatcher `dispatch` function
 - [x] Update new Process calls

### CODE REVIEW

**Comment by alexander-schranz** [comment]
For testing it agains Symfony 5 we need to wait for the behat/behat update but I think @japicoder is currently working on its compatibility.

**Comment by alexander-schranz** [comment]
Did test it locally agains @flug behat PR https://github.com/Behat/Behat/pull/1247 and phpspec and behat did run without errors.

**Comment by drupol** [comment]
Can't wait for this.

**Comment by ciaranmcnulty** [comment]
Great stuff, thank you!

Sorry I didn't make the hackday

**Pull request merged**
