### PR TITLE
Add Symfony 4 support to PhpSpec

### PR DESCRIPTION
**Pull request by sroze**

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Yaml parser got stricter?

**Comment by sroze** [comment]
Yes sir.

**Comment by sroze** [comment]
It's 💚

**Comment by kornrunner** [comment]
Any chance of tagging this as a patch? Thanks!

**Comment by ciaranmcnulty** [comment]
@kornrunner this was included in 4.2.3

**Pull request merged**
