### PR TITLE
Use single quotes; add document markers; remove xdebug in non-hhvm en…

### PR DESCRIPTION
**Pull request by shrikeh**
…vironments

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Are the document markers important?

What difference do the single-quotes make?

**Comment by stof** [comment]
-1 for document markers

**Comment by shrikeh** [comment]
Document markers in YAML are important and often overlooked; they are explicit calls that the document begins and ends. For someone who uses YAML all the time, when I see YAML docs without them, it's the same as I'm sure when @stof sees `foo = new stdClass;` - yes, you don't need the brackets after the class name to instantiate the class, because the PHP parser lets you get away with it.

Single quotes are simply the same as per PHP; if something is only a string, it should be wrapped in single quotes to ensure it does not ever evaluate.

**Comment by stof** [comment]
@shrikeh when the file contains a single document (which is always the case for config files, as there is no point putting multiple documents in the config file), I don't see any benefit about using an explicit document rather than a bare document. It only makes things harder to read for people not aware of the full YAML spec.

**Comment by shrikeh** [comment]
*shrugs*

**Pull request closed without merging**
