### PR TITLE
Add PhpSpec logo in SVG and original Sketch format

### PR DESCRIPTION
**Pull request by everzet**
Original was drawn in [Sketch](https://www.sketchapp.com/) by me, so we should never get any copyright problems.

### CODE REVIEW

**Comment by stof** [comment]
does it really make sense to put this in the source code of the tool ? We could create a ``phpspec/assets`` repository instead to store such things

**Comment by everzet** [comment]
@stof my thinking process was that as we already store documentation in the same repo, we might as well store other assets in

**Comment by stof** [comment]
@everzet but the doc is here because it should be versioned together with the code, as it evolves with it.

**Comment by everzet** [comment]
@stof true. @ciaranmcnulty feel free to move this PR to the separate repo if you think it's a better idea.

**Comment by ciaranmcnulty** [comment]
Possibly the static asset can be stored somewhere else? @stof you make a good point.

Would be great to have a page in the docs about the logo and with some sort of specific license.

**Comment by ciaranmcnulty** [comment]
I guess the fact we might make it different in future (albeit no current plans) means it may make sense to version it with the docs?

**Comment by stof** [comment]
@ciaranmcnulty I don't think so. If we change the PhpSpec branding, it should just replace the older logo (we can still find older versions of the logo thanks to the git history of this other repo)

**Comment by ciaranmcnulty** [comment]
I'll make a separate repository..

**Comment by ciaranmcnulty** [comment]
@stof @everzet I finally got around to splitting these commits into a new repo - see phpspec-logo

**Pull request closed without merging**
