### PR TITLE
DI (option 2, phase 3)

### PR DESCRIPTION
**Pull request by Sam-Burns**
Depends on: https://github.com/phpspec/phpspec/pull/935
Depends on: https://github.com/phpspec/phpspec/pull/938

Creates a new Console Manager object.  Using this, removes all usages of `ServiceContainer::set()` from the `Application` class.

Though (possibly) valuable on its own, this is also a prerequisite for other changes to the dependency injection situation, to be proposed shortly.

This PR is based on previous ones, still open at time of writing. The proposed changes which are unique to this PR can be viewed in the [branch diff](https://github.com/Sam-Burns/phpspec/compare/di-option-2-phase-2...Sam-Burns:di-option-2-phase-3)

### CODE REVIEW

**Comment by stof** [comment]
What is the value of this ConsoleManager ? This looks like a separate container for only some of the services instead of using the normal container.

**Comment by Sam-Burns** [comment]
The value is that using the service locator as a registry, and setting things to it in the application object, is a pretty serious code smell.  By using the `ConsoleManager` as a smaller, more manageable registry, we get closer to actual dependency injection.

**Comment by stof** [comment]
@Sam-Burns what we have today is a service container, which is getting configured.
The fact that the Input service is not instantiated by the container itself is an implementation detail today, while your PR forces any service needing to consume it to know about the fact that it is special instead of being available as a service.
I consider the current code cleaner than your proposal in this regard.

**Comment by Sam-Burns** [comment]
This PR removes four uses of `ServiceContainer::set()` from inside the `Application` class.  Do you have an alternative suggestion as to how to get rid of those, so we can stop using the container as a registry pattern and service locator?

**Comment by stof** [comment]
@Sam-Burns this ``set`` calls are part of the container configuration, because we are required to use the existing Input and Output objects rather than instantiating it inside the container.
note that the Symfony DI component aknowledges this use case too. This is exactly what synthetic services are for.

**Comment by Sam-Burns** [comment]
Closing, as encompassed in https://github.com/phpspec/phpspec/pull/942

**Pull request closed without merging**
