### PR TITLE
Allow PHPUnit 11

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by XWB** [comment]
@ciaranmcnulty Do you have time to merge this change and tag a new release?

**Comment by NenadStef** [comment]
@XWB @ciaranmcnulty Hi, do you have any idea when this patch is going to be released?

**Comment by XWB** [comment]
ping @ciaranmcnulty

**Review by jakzal — APPROVED** [review]

**Comment by jakzal** [comment]
Once rebased, a build should be triggered. Make sure one of the builds covers PHPUnit 11 please.

**Comment by jakzal** [comment]
None of the builds actually installed PHPUnit 11.

**Review by jakzal — CHANGES_REQUESTED** [review]
PHPUnit 11 cannot be currently installed with PhpSpec:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpunit/phpunit ^11.0 -> satisfiable by phpunit/phpunit[11.0.0, ..., 11.4.3].
    - Root composer.json requires vimeo/psalm ^4.3 || ^5.2 -> satisfiable by vimeo/psalm[4.3.0, ..., 4.30.0, 5.2.0, ..., 5.26.1].
    - vimeo/psalm[4.9.0, ..., 4.10.0] require nikic/php-parser ^4.12 -> satisfiable by nikic/php-parser[v4.12.0, ..., v4.19.4].
    - vimeo/psalm[4.11.0, ..., 4.30.0] require nikic/php-parser ^4.13 -> satisfiable by nikic/php-parser[v4.13.0, ..., v4.19.4].
    - vimeo/psalm[4.3.0, ..., 4.7.2] require nikic/php-parser ^4.10.1 -> satisfiable by nikic/php-parser[v4.10.1, ..., v4.19.4].
    - vimeo/psalm[4.7.3, ..., 4.8.1] require nikic/php-parser ^4.10.5 -> satisfiable by nikic/php-parser[v4.10.5, ..., v4.19.4].
    - vimeo/psalm[5.14.0, ..., 5.21.1] require nikic/php-parser ^4.16 -> satisfiable by nikic/php-parser[v4.16.0, ..., v4.19.4].
    - Conclusion: don't install nikic/php-parser[v5.3.1] | install one of vimeo/psalm[4.3.0, ..., 4.30.0, 5.14.0, ..., 5.21.1] (conflict analysis result)
    - Conclusion: install nikic/php-parser v5.3.1 (conflict analysis result)
    - You can only install one version of a package, so only one of these can be installed: nikic/php-parser[v4.10.1, ..., v4.19.4, v5.0.0, ..., v5.3.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by XWB** [comment]
That's a pity. If the issue is related to a 3rd party package, I suppose this cannot be fixed?

**Comment by jakzal** [comment]
https://github.com/vimeo/psalm/pull/10567
https://github.com/vimeo/psalm/discussions/10701

 > Psalm 6 is a blocker to upgrade to PHPUnit 11

**Comment by XWB** [comment]
Alright, we will have to wait.

**Comment by jakzal** [comment]
Using ohar installation for psalm could work: https://github.com/vimeo/psalm/blob/5.x/docs/running_psalm/installation.md#using-the-phar

**Pull request closed without merging**
