### PR TITLE
Allow to describe a class providing a namespace with leading backslash

### PR DESCRIPTION
**Pull request by mheki**
Fixes: #928

Conflicts:
 - spec/PhpSpec/Locator/PSR0/PSR0LocatorSpec.php

### CODE REVIEW

**Comment by stof** [comment]
:+1: 

@ciaranmcnulty the 5.3.3 build should be removed from the 2.5 branch IMO. This Travis image is just unusable as it does not have openssl

**Comment by ciaranmcnulty** [comment]
@stof yeah probably if there's no sane solution.

**Comment by stof** [comment]
@ciaranmcnulty the same solution is to stop using the 5.3.3 environment.
Testing against the latest 5.3 is enough guarantee IMO. Other minor versions of PHP are only tested against their latest release (or at least the latest at the time of the Travis environment update...)

**Comment by ciaranmcnulty** [comment]
@stof 5.3.3 is a special case where we also test against the lowest-preferred composer deps. As it's impractical I'm removing it though :-/

**Comment by ciaranmcnulty** [comment]
Thanks @mheki!

**Pull request merged**
