### PR TITLE
Use extension to detect PHP version

### PR DESCRIPTION
**Pull request by ciaranmcnulty**
I wrote an extension with this sort of testing in mind; replaces the existing mechanism for skipping tests based on PHP version

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Anyone know what's up with Scrutiniser?

**Comment by Sam-Burns** [comment]
@ciaranmcnulty Yeah, we need a new version of the `bossa/phpspec2-expects` thing. I'll see what I can do.

**Comment by mheki** [comment]
@Sam-Burns https://github.com/BossaConsulting/phpspec2-expect/pull/25

**Comment by stof** [comment]
@ciaranmcnulty loçoks like it considers the version of the root package as being dev-2.5, which does not make sense. I suspect they have a bug in their code handling cyclic composer dependencies

**Comment by ciaranmcnulty** [comment]
Maybe should report it to Composer :-/

**Comment by stof** [comment]
The issue is not in composer IMO, but in the value which is set by Scrutinizer in the ``COMPOSER_ROOT_VERSION`` constraint. I suspect they just set it as ``dev-$BRANCH``, without taking versionned branches into account.

**Comment by ciaranmcnulty** [comment]
You're right, I get the same error output if I try `COMPOSER_ROOT_VERSION=dev-2.5 composer install
` this will probably be a problem ongoing then :-/

**Comment by ciaranmcnulty** [comment]
Assuming scrutiniser can be ignored, I'd appreciate feedback

**Comment by stof** [comment]
@ciaranmcnulty you should report it to Scrutinizer though.

A workaround might be to add a branch alias from ``dev-2.5`` to ``2.5.x-dev`` in the composer.json (with a comment in ``_comment`` explaining that this is to workaround a scrutinizer bug)

**Comment by stof** [comment]
Looks good to me otherwise

**Comment by ciaranmcnulty** [comment]
Thanks, I wasn't sure about using an egotistically-named extension :-P

Might be useful for similar cases in Behat?

**Comment by ciaranmcnulty** [comment]
I emailed scrutiniser support

**Comment by stof** [comment]
have you tried my suggestion for a workaround ?

**Comment by ciaranmcnulty** [comment]
I backported the fix from master that removes the circular dependency

**Pull request merged**
