### PR TITLE
feat: allow symfony 7

### PR DESCRIPTION
**Pull request by Chris53897**
I am not sure if the ci testruns already covers symfony 7 installation

### CODE REVIEW

**Comment by ste93cry** [comment]
Symfony 7 has been released. @ciaranmcnulty can we move forward with this PR?

**Comment by loic425** [comment]
@Chris53897 could you please the issues (cf CI)

**Comment by Chris53897** [comment]
The ci (Psalm) error, are not related to this PR, and should be fixed in an seperate PR in my eyes.
I will go to vaccation tomorrow. Maybe someone else can do the PR?

**Comment by Chris53897** [comment]
See https://github.com/Chris53897/phpspec/actions/runs/7214166989 for example

**Comment by ciaranmcnulty** [comment]
Thanks for this @Chris53897 I'm closing only because #1454 is more complete, I'll credit you in the changelog

**Pull request closed without merging**
