### PR TITLE
Ensures named parameters are correctly passed by

### PR DESCRIPTION
**Pull request by gquemener**
This should resolve https://github.com/phpspec/phpspec/issues/1334

### CODE REVIEW

**Comment by gquemener** [comment]
Does it answer your concerns @ciaranmcnulty ?

**Comment by ciaranmcnulty** [comment]
It does somewhat, we'd also need to look at the various constructors I guess, and of course Prophecy upstream

**Comment by ciaranmcnulty** [comment]
Build failure seems to be due to `symfony/polyfill-mbstring`

**Comment by ciaranmcnulty** [comment]
The psalm issue is fixed already, just waiting on a release https://github.com/vimeo/psalm/pull/4967

**Comment by ciaranmcnulty** [comment]
Thanks @gquemener ! I'll keep the issue open for other cases

**Pull request merged**
