### PR TITLE
Check for error when test method parameter is pass-by-reference

### PR DESCRIPTION
**Pull request by andho**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Is this resolved then or not?

**Comment by ciaranmcnulty** [comment]
The issue isn't resolved, the PR was closed because it seemed dead for a year.

**Comment by sagikazarmark** [comment]
Is it on some kind of todo list?

**Comment by ciaranmcnulty** [comment]
Feel free to open an issue; I'm not aware of anyone working on it. You can if you like :)

**Comment by nixilla** [comment]
see https://github.com/phpspec/phpspec/issues/239#issuecomment-344580176 for workaround

**Pull request closed without merging**
