### PR TITLE
Fix: Simplify FQCN

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] simplifies a few unnecessary fully qualified class names

### CODE REVIEW

**Comment by localheinz** [comment]
@ciaranmcnulty 

To be honest, I'm a bit confused - there are so many fully qualified class names, while at the same time, these are imported, is there a reason I'm unaware of why that is done?

**Comment by ciaranmcnulty** [comment]
No idea, to be honest. I think some IDEs have historically been poor at resolving class aliases, which may be a reason?

**Comment by GrahamCampbell** [comment]
I'm REALLY :-1: on this. PHPDoc should be human readable IMO. It should be immediately obvious to a human on first read what the types are.

**Comment by ciaranmcnulty** [comment]
@GrahamCampbell Does the FQCN make it more obvious what the type is? I'm not convinced it does.

**Comment by ciaranmcnulty** [comment]
@localheinz Merging your other PRs seems to have caused a problem with the merge here

**Comment by GrahamCampbell** [comment]
> Does the FQCN make it more obvious what the type is? I'm not convinced it does.

`Foo` is totally non obvious, but `Vendor\Foo\Baz\Foo` is super clear what the type is.

**Comment by ciaranmcnulty** [comment]
In typehints or class instantiation, we use short names because it is easier to grok what the code is doing if we're not seeing FCQNs all over the place. For me the same logic applies to docblocks.

**Comment by localheinz** [comment]
@ciaranmcnulty 

Rebased!

**Comment by everzet** [comment]
@GrahamCampbell if `Foo` doesn't give you a clear idea on what type is it, then `Foo` is a bad name. I see this all the time, people think that namespace is part of the class name - IMO it is not, it is a context.

**Comment by ciaranmcnulty** [comment]
Thanks for this and the other improvements @localheinz

**Comment by localheinz** [comment]
You're welcome, @ciaranmcnulty!

**Pull request merged**
