### PR TITLE
Test on PHP 7.0, allow it to fail.

### PR DESCRIPTION
**Pull request by frankdejonge**

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Nice, thanks.

How stable is the PHP7 feature set? I'm behind on internals.

What I mean is: at what point is it worth investing time trying to make it work?

**Comment by frankdejonge** [comment]
@ciaranmcnulty judging by the PHP 7 release timeline (https://wiki.php.net/rfc/php7timeline) I'd say investing time into "getting it to work" would be somewhere around September-ish. Though I think it's good to see what the project does on this version regardless. In my project, the phpspec tests fail on php 7 (only), which has to do with the `let()` double resolving. I figured this would put that on the radar, if it still exists by that time.

**Comment by ciaranmcnulty** [comment]
Makes sense to me, and we 'fail early' so it won't delay build results.

**Comment by ciaranmcnulty** [comment]
Would it make sense for the next release to specify a composer dependency on PHP <7.0 ?

**Comment by frankdejonge** [comment]
@ciaranmcnulty you could specify the php version as `^5.3.3` which is the equivalent of `>=5.3.3, <6.0.0`.

**Comment by ciaranmcnulty** [comment]
I'm a bit nervous about ^ in the next tagged release, and whether it'll break people using stable composer releases

**Comment by stof** [comment]
@ciaranmcnulty I would not change the requirement to forbid PHP 7 for now (unless you first debug the reason for each failure to know whether it is an intended BC break in PHP 7 or a regression)

**Comment by ciaranmcnulty** [comment]
True, it's probably best to worry more about it later.

**Comment by frankdejonge** [comment]
I agree with @stof, especially at this time it's good to be able to install it, even if it fails. This way bugs can be found and fixed. Also, I reckon you'd want to get the project up to speed with that version eventually anyway.

**Pull request merged**
