### PR TITLE
Updating authors

### PR DESCRIPTION
**Pull request by Sam-Burns**
Where credit's due

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Not sure having multiple authors is correct; there aren't just 3 of us.

**Comment by Sam-Burns** [comment]
Well, there aren't just two... Would you prefer to see the `authors` section removed?  I'd rather it at least mentions the lead maintainer if it's staying.

**Comment by ciaranmcnulty** [comment]
What do other projects do?

**Comment by henrikbjorn** [comment]
I have seen other projects, just listen Contributors as the authors.

**Comment by shanethehat** [comment]
Maybe authors should be anyone with write access?

**Comment by Sam-Burns** [comment]
I think @ciaranmcnulty is just too modest to push the merge button on this one.  Current `authors` section is a bit misleading though, to be fair.  Maybe current and previous leads should be mentioned, as well as 'various contributors'?

**Comment by stof** [comment]
As @ciaranmcnulty is the lead now, I think it is logical to have him in the list here

**Comment by ciaranmcnulty** [comment]
It appears the `authors` key is optional

**Comment by ciaranmcnulty** [comment]
Very well

**Pull request merged**
