### PR TITLE
add an empty line at the end of generated files

### PR DESCRIPTION
**Pull request by nsitbon**
[PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#22-files) requires each PHP files to be ended with an empty line. This PR enforces this rule.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
There is already one isn;t there?

**Comment by nsitbon** [comment]
running 
`vendor/bin/phpspec desc Foo`
generates a spec file without ending empty line.

**Comment by ciaranmcnulty** [comment]
We currently have a LF at the end, not a blank line. I personally don't like having a blank line and don't see many projects checking for that, but it does seem to be a PSR-2 requirement.

**Comment by ciaranmcnulty** [comment]
Some debate here https://groups.google.com/forum/#!topic/php-fig/PSzmcFVQst0

**Comment by ciaranmcnulty** [comment]
We currently end with `}\n` and PSR-2 seems to imply we should end with `}\n\n`

Even though that's stupid IMO

**Comment by nsitbon** [comment]
My bad : vim was hiding the trailing empty line. I'm sorry for having wasted your time.
The good point is that it allows me to catch a bug in behat.

**Pull request closed without merging**
