### PR TITLE
Allow sebastian/exporter v3

### PR DESCRIPTION
**Pull request by remicollet**
As there is no change in code

### CODE REVIEW

**Comment by stof** [comment]
@ciaranmcnulty as the only BC break is removing support for older PHP versions, I suggest we also backport it to older versions (see #1073). What do you think ?

**Comment by stof** [comment]
@ciaranmcnulty any answer to my comment ?

**Comment by ciaranmcnulty** [comment]
I merged your backport to allow 2.0, will do the same with 3

**Comment by stof** [comment]
OK, then opening the PR

**Comment by stof** [comment]
@ciaranmcnulty PR opened

**Comment by stof** [comment]
@ciaranmcnulty can you then tag a 2.5.x release with the backports in it ?

**Comment by ciaranmcnulty** [comment]
I will when I've gone through the rest of the open PRs

**Comment by stof** [comment]
thanks

**Pull request merged**
