### PR TITLE
Rework appveyor

### PR DESCRIPTION
**Pull request by Taluu**
As done in behat. :}

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
It seems to be failing

**Comment by Taluu** [comment]
Behat tests seems to fail, but then we would need to check if it run on the current appveyor config... Could you trigger a build from master or something ?

**Comment by jakzal** [comment]
@Taluu for build fix see #1205

**Comment by ciaranmcnulty** [comment]
Great! Thanks

**Pull request merged**
