### PR TITLE
check for event dispatcher contract Closes #1294

### LINKED ISSUE #1294: Argument 2 passed to EventDispatcher::dispatch() must be an instance of Event
I updated `phpspec/phpspec (5.1.2 => 6.1.1)`. I'm using `symfony/symfony: v4.2.12`.

Started getting:

```
Uncaught TypeError: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, instance of PhpSpec\Event\SuiteEvent given, called in vendor/phpspec/phpspec/src/PhpSpec/Util/DispatchTrait.php on line 25 and defined in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:37
    Stack trace:
    #0 vendor/phpspec/phpspec/src/PhpSpec/Util/DispatchTrait.php(25): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('beforeSuite', Object(PhpSpec\Event\SuiteEvent))
    #1 vendor/phpspec/phpspec/src/PhpSpec/Runner/SuiteRunner.php(52): PhpSpec\Runner\SuiteRunner->dispatch(Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(PhpSpec\Event\SuiteEvent), 'beforeSuite')
    #2 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php on line 37
```

### PR DESCRIPTION
**Pull request by akuzia**

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Now that master is passing can you rebase please? 

It looks like some tests need updating

**Comment by akuzia** [comment]
@ciaranmcnulty kinda done

**Comment by ciaranmcnulty** [comment]
Yep it looks like the corresponding test isn't updated

**Comment by akuzia** [comment]
I did not know why, but when I've tried to run specs I've got tons of var_dump output and no usefull information. So I've stick without fixing tests :confused:

**Comment by ciaranmcnulty** [comment]
Ok I've fixed the tests but couldn't push to your branch so I've opened #1307, lets continue there

**Pull request closed without merging**
