### PR TITLE
Update ScalarMatcher.php

### PR DESCRIPTION
**Pull request by DonCallisto**
Implemented `return null` in order to satisfy return type hinting.

### CODE REVIEW

**Comment by DonCallisto** [comment]
It seems that failing tests are not related with this PR.

**Comment by Sam-Burns** [comment]
@DonCallisto I can see your issue with the failing tests. We need to introduce a change such as https://github.com/phpspec/phpspec/pull/1224 to stop the tests from failing. The error was not caused by your PR.

**Comment by DonCallisto** [comment]
@ciaranmcnulty I've rebased to master after @Sam-Burns PR merge. Now should be ok to merge this

**Comment by DonCallisto** [comment]
No, it's because we have typehint on the return type and `none` != `null` so this code will produce a fatal error

**Comment by ciaranmcnulty** [comment]
Oh! of course. Thanks!

**Comment by ciaranmcnulty** [comment]
Is it possible to write a test?

**Comment by DonCallisto** [comment]
Yes, of course. I'll write them ASAP.

**Comment by DonCallisto** [comment]
@ciaranmcnulty I've added requested tests. Can you take a look?
Thanks.

**Comment by ciaranmcnulty** [comment]
Really nice, thanks

**Pull request merged**
