### PR TITLE
Simplifed version constraints

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Sent again for future merge as suggested.

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Scrutinizer seems happy now

**Comment by stof** [comment]
@ciaranmcnulty can you rebase to trigger a new scrutinizer analysis to be sure it is happy ?

**Comment by GrahamCampbell** [comment]
Done.

**Comment by ciaranmcnulty** [comment]
I think sufficient time has passed now that this can merge if scrutinizer is happy. By the time we do a next release everyone who's not updated `composer` will have been getting warnings for a while about updating.

**Pull request merged**
