### PR TITLE
Adopt PSR-2 coding standards

### PR DESCRIPTION
**Pull request by ciaranmcnulty**
* Added `CONTRIBUTING.md` specifying PSR-2
* Added `php_codesniffer` to travis
* Fixed all errors

This will make me less grumpy when people tell me my brackets are 'wrong'

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why not use https://styleci.io?

**Comment by ciaranmcnulty** [comment]
@GrahamCampbell Looks good - I want a way to check locally myself before commit - is that possible?

**Comment by stof** [comment]
@ciaranmcnulty stylecu.io just runs PHP-CS-Fixer

-1 for running the style checks on Travis itself. I prefer keeping the Travis build status for the status of tests only.
An option would be to add a failure condition on Scrutinizer to make it report a failed analysis when there are new CS issues.

**Comment by ciaranmcnulty** [comment]
I'm confused why this is working locally for me and failing, BTW

I'll remove the CI elements and look at styleci.io or scrutinizer options, thanks guys

**Comment by ciaranmcnulty** [comment]
OK I've taken out the CI element so the PR is just fixes

**Comment by GrahamCampbell** [comment]
> -1 for running the style checks on Travis itself. I prefer keeping the Travis build status for the status of tests only.

Yep, agreed. You can use https://styleci.io/ to check pushed commits and php-cs-fixer locally.

**Comment by GrahamCampbell** [comment]
If you set styleci to use the "psr2" preset, that's the same as using the psr2 level on php-cs-fixer.

**Comment by GrahamCampbell** [comment]
We can't use .phpcs config files on styleci because for obvious reasons, we can't allow user provided php code to be executed on our workers.

**Comment by ciaranmcnulty** [comment]
Can I exclude the `src` folder some other way? If not, we can't use style

**Comment by GrahamCampbell** [comment]
We're working on that, but we'd accept a pull request to add that feature in the meanwhile.

**Pull request merged**
