### PR TITLE
[WIP] Output ignored specs

### PR DESCRIPTION
**Pull request by gquemener**
Discussion has started on #1200 

## Todo

- [x] update progress formatter
- [ ] update pretty formatter
- [ ] update dot formatter
- [ ] update html formatter
- [ ] update json formatter ?

### CODE REVIEW

**Comment by gquemener** [comment]
Here's a preview of the different outputs:

Screenshot from 2019-10-28 15-14-19
Screenshot_2019-10-28 PHPSpec results

**Comment by ciaranmcnulty** [comment]
Looks nice so far from the screengrabs

I've been meaning to do a refactor around IO for a while - it's possible we could split some of these responsibilities away from the Formatter (will open another issue)

**Comment by gquemener** [comment]
Sure thing, let me know if you'd like some help with that too :+1:

**Comment by ciaranmcnulty** [comment]
@gquemener What's the status here? Does it need review from me?

**Comment by gquemener** [comment]
@ciaranmcnulty there might have been a misunderstanding back in the days, I must have thought you'd be tackling the refactoring you mentioned before I continue on this PR.

Unfortunately, time passed and I kind of forget about it...

What's your opinion nowadays? Should the refactoring still be performed? Should this feature be developed no matter what?

**Comment by ciaranmcnulty** [comment]
This auto-closed when I removed `master`

Re-open if you have energy :-)

I'll take it without the refactor, it seems like that was a source of inertia and I apologise

**Pull request closed without merging**
