### PR TITLE
Add shouldYield / shouldStartYielding methods to Subject

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Ah! good catch thanks

**Comment by pamil** [comment]
I'll be grateful for a bugfix release containing this one :)

**Comment by ciaranmcnulty** [comment]
It'll be a new minor version... will take a look this weekend

**Comment by pamil** [comment]
Awesome, thanks! 🎉

**Comment by jakzal** [comment]
:+1:

**Pull request merged**
