### PR TITLE
[3.0 migration guide] Fixed `PhpSpec\Extension`

### PR DESCRIPTION
**Pull request by gnugat**
removed duplicated line, and fixed the actual new FQCN.

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Hm this actually looks wrong at http://www.phpspec.net/en/latest/manual/upgrading-to-phpspec-3.html

Any idea how to properly escape these?

**Comment by gnugat** [comment]
Probably using back ticks instead of asterisks

**Comment by gnugat** [comment]
Actually, it's double backticks (because we use RST). There's a working example in [Prophet Objects](https://raw.githubusercontent.com/phpspec/phpspec/master/docs/manual/prophet-objects.rst)

**Comment by ciaranmcnulty** [comment]
Great, thanks

**Pull request merged**
