### PR TITLE
PHP 7 typehint support

### PR DESCRIPTION
**Pull request by ciaranmcnulty**
This enables PHP7 support by doing a slightly-nasty rewrite of the spec file as it's being included

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
I've changed the title of this as it's now working / mergable.

I'd appreciate feedback; there are some parts of the design (mostly the rewriter) that probably need to be refactored

**Comment by everzet** [comment]
Great job! `TypeHintRewriter` begs for refactoring though

**Comment by everzet** [comment]
Other that that, big :+1: from me.

**Comment by sroze** [comment]
:tada:

**Comment by ciaranmcnulty** [comment]
@everzet yeah `TypeHintRewriter` is a monolith that I'll break down before merging.

I anticipate once this is merged that I'll do an `alpha` release - there must be edge cases that aren't covered, especially with the namespace syntax/FQCN resolving

**Comment by Elfiggo** [comment]
:8ball: Ship It!

**Pull request merged**
