### PR TITLE
Adding PSR2 inspections to scrutinizer

### PR DESCRIPTION
**Pull request by ciaranmcnulty**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The trouble with scrutinizer is that it never actually fails the build for bad cs, so it's kind of pointless.

**Comment by ciaranmcnulty** [comment]
@GrahamCampbell I've deliberately broken this build to show that it does in fact fail for bad CS if you ask it to

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/wL73 Looks like it's passing to me?

**Comment by ciaranmcnulty** [comment]
I meant I broke it to test, I fixed again before merge.

Any issues labelled 'Coding Style' cause a build failure.

**Comment by GrahamCampbell** [comment]
Nice.

**Comment by GrahamCampbell** [comment]
Still, scrutinizer doesn't provide a diff for every fix, infact it doesn't for most fixes, unlike styleci, which provides a diff for everything.

**Comment by ciaranmcnulty** [comment]
True. It does suppose php-ci-fixer but not sure if it patches.

If styleci supports excluded paths in future I'll consider a switch if you want to PR. At the moment we're running a scrutiniser build anyhow so it makes sense to use it.

**Comment by GrahamCampbell** [comment]
Sure. I'll let you know when we ship that feature. The thing holding us is just none of us have enough free time, lol.

**Pull request merged**
