### PR TITLE
Fix return type for ObjectStateMatcher::negativeMatch()

### PR DESCRIPTION
**Pull request by nightlinus**
Is there any case for returning ?DelayedCall, maybe just void would be right?

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Can you explain why this is an improvement?

The return type is dictated by the parent `Matcher` interface; some matchers return a `DelayedCall`

**Comment by nightlinus** [comment]
Thank you for quick reply.
Ok, just asked about need of `DelayedCall`. In any case this pr fixes missing `return null;` or one got error
`[err:TypeError("Return value of PhpSpec\Matcher\ObjectStateMatcher::negativeMatch() must be an instance of PhpSpec\Wrapper\DelayedCall or null, none returned")]`

**Comment by ciaranmcnulty** [comment]
Oh I see, I wonder why the tests didn't catch it at all?

**Comment by nightlinus** [comment]
let me add one positive test

**Comment by nightlinus** [comment]
Ah, all is valid behaviour when using non-phar global version.

**Comment by ciaranmcnulty** [comment]
Thanks!

**Pull request merged**
