### PR TITLE
PHP 8.1 fixes

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Looking again at the RFC, we may be able to just add the `#[ReturnTypeWillChange]` attribute, at least until PHP 9.0

**Comment by driesvints** [comment]
@ciaranmcnulty seems like Psalm is borking. I'm sure the syntax for the attribute is correct.

**Comment by driesvints** [comment]
@ciaranmcnulty can you maybe do that? I've never worked with Psalm myself I'm afraid.

**Comment by GrahamCampbell** [comment]
Psalm also has a baseline functionality like phpstan, if you wanna quickly generate and add to that.

**Comment by ciaranmcnulty** [comment]
@GrahamCampbell I want to keep the exclusions specific

**Comment by GrahamCampbell** [comment]
Can generate it and then move the generated code into the other file. :trollface:

**Comment by GrahamCampbell** [comment]
psalm also has a `@psalm-suppress` annotation you can add in phpdoc. maybe that's preferable here.

**Comment by ciaranmcnulty** [comment]
Hm, there are more issues...

**Comment by ciaranmcnulty** [comment]
I guess those tests all need proper stubs

**Comment by jaylinski** [comment]
I fixed the remaining issues in #1407, please have a look.

**Pull request closed without merging**
