### PR TITLE
Be consistent with ^ notation

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I've replaced `~` with `^` in all places where it does not change the behaviour.

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
What's the benefit?

**Comment by unexge** [comment]
@ciaranmcnulty AFAIK, `~1.5` -> `>=1.5 <1.6`, `^1.5` -> `>=1.5.0 <2.0.0`, it also [recommended](https://getcomposer.org/doc/articles/versions.md#caret) by composer.

**Comment by ciaranmcnulty** [comment]
@unexge I don't think you are correct

**Comment by GrahamCampbell** [comment]
> AFAIK, ~1.5 -> >=1.5 <1.6

That's not correct I'm afraid.

**Comment by GrahamCampbell** [comment]
> That's not correct I'm afraid.

That describes what `~1.5.0` would do.

**Comment by ciaranmcnulty** [comment]
I don't see a reason to change these

**Comment by GrahamCampbell** [comment]
The fact you randomly have a `^2.7|~3.0` along with those `~2.7|~3.0` is very odd.

**Pull request closed without merging**
